### ISSUE TITLE
Relative order doesn't work with parametrize

### ISSUE THREAD

**Issue by GentleEnvy** [pytest-dev/pytest-order#38]
I added the parametrize decorator to one test from the [documentation](https://pytest-dev.github.io/pytest-order/dev/usage.html#order-relative-to-other-tests) and order stopped working.

```
@pytest.mark.order(after="test_second")
def test_third():
    assert True

@pytest.mark.parametrize('param', [True])
def test_second(param):
    assert param

@pytest.mark.order(before="test_second")
def test_first():
    assert True
```

As a result, I get 2 warnings and the usual order of tests:

WARNING: cannot execute test relative to others: test_second - ignoring the marker.
WARNING: cannot execute test relative to others: test_second - ignoring the marker.collected 3 items

tests/test_func.py::test_third 
tests/test_func.py::test_second[True] 
tests/test_func.py::test_first

**Comment by mrbean-bremen** [comment]
The problem is that `pytest-order` uses the full name of the test, which includes the parameter - in your case that would be "test_second[True]", e.g.
```py
@pytest.mark.order(after="test_second[True]")
def test_third():
    assert True
```
should work. 
That is a bit inconvenient, and  I actually have been thinking about adding some special handling for parametrized tests.
I haven't seen anyone using the `before`/`after` feature so far, so I wasn't sure if it is worth it...

**Comment by GentleEnvy** [comment]
I have a lot of parameters that can change. It doesn't suit me. Should I use indexing, or is there a more convenient solution ?
I think with a lot of tests, after/before is better indexing.

**Comment by mrbean-bremen** [comment]
Indexing is one possibility, or you could use `before` with the last parameter, and `after` with the first one, e.g. something like:
```py
@pytest.mark.order(after="test_second[5]")
def test_third():
    assert True

@pytest.mark.parametrize('param', [1, 2, ,3 ,4, 5])
def test_second(param):
    assert param

@pytest.mark.order(before="test_second[1]")
def test_first():
    assert True
```
In the long run, I'm thinking about adding more convenient handling of parametrized tests, maybe to get it to work the way you tried it first. That would not be upwards-compatible, which I think I can live with (the next version will be Python 3 only and will have breaking changes anyway).

**Comment by GentleEnvy** [comment]
It does work, though not perfectly.
Waiting for the new version... Thank you for your work.

**Comment by mrbean-bremen** [comment]
I'll probably make the 1.0 release today - I was planning to anyway, and it is better to do it earlier, as some things have changed.

**Comment by mrbean-bremen** [comment]
@GentleEnvy - can you test with main branch? I just have merged the change in (you will need to change the markers back as you had them in the first place).
If it works for you, I will go for a release.

**Comment by mrbean-bremen** [comment]
@GentleEnvy - will you find the time to test this? Otherwise I'll will just close this and make a new release soon.

**Comment by GentleEnvy** [comment]
Sorry it took so long. I'm not sure if I'm doing everything right, but after the commands:
```
> pip uninstall pytest-order
> pip install git+https://github.com/pytest-dev/pytest-order
```
I get an error:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR> File "D:\Py\Test\vanv\lib\site-packages\_pytest\config\__init__.py", line 1359, in getini
INTERNALERROR> return self._inicache[name]
INTERNALERROR> KeyError: 'automark_dependency'
```

**Comment by mrbean-bremen** [comment]
No probem, and thanks! This is why we need someone else testing this... I had introduced support for the `automark_dependency` option of `pytest-dependency`, but obviously have not tested it without `pytest-dependency` installed. Will try to fix this ASAP.
In the meantime, if you want to test your needed functionality, you may install `pytest-dependency` as a workaround.

**Comment by mrbean-bremen** [comment]
The problem shall be fixed now in main.

**Comment by GentleEnvy** [comment]
It still doesn't seem to work for me. I looked at the code in the debugger a bit and saw that it looks like id_start is being truncated incorrectly:
![Debugger screenshot](https://user-images.githubusercontent.com/58393514/117576528-fdb2f180-b0ee-11eb-810f-e2c527bb163f.png)

**Comment by mrbean-bremen** [comment]
Yes, thank you - I can see this now, I made a clear mistake. I wonder why the tests passed... looks like the tests are not sufficient.

**Comment by mrbean-bremen** [comment]
The tests have passed by chance, because the parameters I used have been very short... sorry for that, I have been sloppy. Will merge the fix in a minute if the tests pass.

**Comment by mrbean-bremen** [comment]
Please check again, if you find the time.

**Comment by GentleEnvy** [comment]
Yes, now it really works for me. Thank you for your work.
